project_id = "ncmofeencqpqhtguxmvy"

[functions.save-workflow]
verify_jwt = true

[functions.execute-workflow]
verify_jwt = true

[functions.list-workflows]
verify_jwt = true

[functions.validate-crm]
verify_jwt = false

[functions.validate-cpf]
verify_jwt = false

[functions.validate-nit]
verify_jwt = false

[functions.validate-cnpj]
verify_jwt = false