project_id = "ncmofeencqpqhtguxmvy"

[functions.diagnostic-assinafy]
verify_jwt = false

[functions.setup-assinafy-webhook]
verify_jwt = true

[functions.save-workflow]
verify_jwt = true

[functions.schedule-trigger]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = false

[functions.continue-workflow]
verify_jwt = true

[functions.list-workflows]
verify_jwt = true

[functions.validate-crm]
verify_jwt = false

[functions.validate-cpf]
verify_jwt = false

[functions.validate-nit]
verify_jwt = false

[functions.validate-cnpj]
verify_jwt = false

[functions.send-signature-request]
verify_jwt = true

[functions.send-templated-email]
verify_jwt = true

[functions.assinafy-webhook]
verify_jwt = false

[functions.process-ocr]
verify_jwt = false

[functions.process-workflow-queue]
verify_jwt = false

[functions.assinafy-webhook-finalizacao]
verify_jwt = false

[functions.enviar-inscricao]
verify_jwt = true

[functions.analisar-inscricao]
verify_jwt = true

[functions.gerar-contrato-assinatura]
verify_jwt = true

[functions.gerar-certificado-credenciamento]
verify_jwt = true

[functions.download-certificado]
verify_jwt = false

[functions.simular-assinatura-contrato]
verify_jwt = true

[functions.publicar-edital]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.test-assinafy-full]
verify_jwt = false

[functions.validate-crm-cfm]
verify_jwt = true

[functions.processar-contrato-orfao]
verify_jwt = true

[functions.processar-alertas-prazos]
verify_jwt = false

